# Generated by Django 3.2.3 on 2021-05-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_account_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='funds',
            field=models.IntegerField(default=0),
        ),
    ]
